# Generated by Django 3.0.6 on 2020-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='annotation_images')),
            ],
        ),
        migrations.CreateModel(
            name='SheetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('sheet', models.FileField(upload_to='upload_sheets')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(upload_to='upload_images'),
        ),
    ]
