# Generated by Django 3.0.6 on 2020-05-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='file_type',
        ),
    ]
