# Generated by Django 3.0.6 on 2020-06-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20200613_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='side',
            field=models.CharField(default='3H', max_length=10),
            preserve_default=False,
        ),
    ]
