# Generated by Django 3.0.6 on 2020-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_imageupload_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='sift_cropped_images')),
                ('side', models.CharField(max_length=10)),
            ],
        ),
    ]
