version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: jiangyun123456

    migration:
        build: .
        command: python3 manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - db

    web:
        build: .
        command: 
            - /bin/sh
            - -c
            - |
                python3 manage.py initadmin
                python3 manage.py runserver 0.0.0.0:8004
        volumes:
            - .:/usr/src/app
        ports:
            - "8004:8004"
        depends_on:
            - db
            - migration
