# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/jyservice.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/jyservice.proto',
  package='JYService',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18protocol/jyservice.proto\x12\tJYService\"j\n\x15TrainParameterRequest\x12\x15\n\rlearning_rate\x18\x01 \x01(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x0e\n\x06if_gpu\x18\x03 \x01(\x05\x12\x16\n\x0eiteration_time\x18\x04 \x01(\x05\"(\n\x16TrainParameterResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"b\n\x10TrainDataRequest\x12\x12\n\nimage_data\x18\x01 \x01(\t\x12\x12\n\nimage_name\x18\x02 \x01(\t\x12\x12\n\nlabel_data\x18\x03 \x01(\t\x12\x12\n\nlabel_name\x18\x04 \x01(\t\"#\n\x11TrainDataResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1d\n\x0cTrainRequest\x12\r\n\x05start\x18\x01 \x01(\t\"-\n\rTrainResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"$\n\x12TrainResultRequest\x12\x0e\n\x06result\x18\x01 \x01(\t\"M\n\x13TrainResultResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\t\x12\x12\n\nimage_name\x18\x03 \x01(\t2\xc0\x02\n\tJYService\x12W\n\x0eTrainParameter\x12 .JYService.TrainParameterRequest\x1a!.JYService.TrainParameterResponse\"\x00\x12J\n\tTrainData\x12\x1b.JYService.TrainDataRequest\x1a\x1c.JYService.TrainDataResponse\"\x00(\x01\x12<\n\x05Train\x12\x17.JYService.TrainRequest\x1a\x18.JYService.TrainResponse\"\x00\x12P\n\x0bTrainResult\x12\x1d.JYService.TrainResultRequest\x1a\x1e.JYService.TrainResultResponse\"\x00\x30\x01\x62\x06proto3'
)




_TRAINPARAMETERREQUEST = _descriptor.Descriptor(
  name='TrainParameterRequest',
  full_name='JYService.TrainParameterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='JYService.TrainParameterRequest.learning_rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='JYService.TrainParameterRequest.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='if_gpu', full_name='JYService.TrainParameterRequest.if_gpu', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iteration_time', full_name='JYService.TrainParameterRequest.iteration_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=145,
)


_TRAINPARAMETERRESPONSE = _descriptor.Descriptor(
  name='TrainParameterResponse',
  full_name='JYService.TrainParameterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='JYService.TrainParameterResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=187,
)


_TRAINDATAREQUEST = _descriptor.Descriptor(
  name='TrainDataRequest',
  full_name='JYService.TrainDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='JYService.TrainDataRequest.image_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='JYService.TrainDataRequest.image_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_data', full_name='JYService.TrainDataRequest.label_data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_name', full_name='JYService.TrainDataRequest.label_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=287,
)


_TRAINDATARESPONSE = _descriptor.Descriptor(
  name='TrainDataResponse',
  full_name='JYService.TrainDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='JYService.TrainDataResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=324,
)


_TRAINREQUEST = _descriptor.Descriptor(
  name='TrainRequest',
  full_name='JYService.TrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='JYService.TrainRequest.start', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=355,
)


_TRAINRESPONSE = _descriptor.Descriptor(
  name='TrainResponse',
  full_name='JYService.TrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='JYService.TrainResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='JYService.TrainResponse.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=402,
)


_TRAINRESULTREQUEST = _descriptor.Descriptor(
  name='TrainResultRequest',
  full_name='JYService.TrainResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='JYService.TrainResultRequest.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=440,
)


_TRAINRESULTRESPONSE = _descriptor.Descriptor(
  name='TrainResultResponse',
  full_name='JYService.TrainResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='JYService.TrainResultResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='JYService.TrainResultResponse.image_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='JYService.TrainResultResponse.image_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=519,
)

DESCRIPTOR.message_types_by_name['TrainParameterRequest'] = _TRAINPARAMETERREQUEST
DESCRIPTOR.message_types_by_name['TrainParameterResponse'] = _TRAINPARAMETERRESPONSE
DESCRIPTOR.message_types_by_name['TrainDataRequest'] = _TRAINDATAREQUEST
DESCRIPTOR.message_types_by_name['TrainDataResponse'] = _TRAINDATARESPONSE
DESCRIPTOR.message_types_by_name['TrainRequest'] = _TRAINREQUEST
DESCRIPTOR.message_types_by_name['TrainResponse'] = _TRAINRESPONSE
DESCRIPTOR.message_types_by_name['TrainResultRequest'] = _TRAINRESULTREQUEST
DESCRIPTOR.message_types_by_name['TrainResultResponse'] = _TRAINRESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainParameterRequest = _reflection.GeneratedProtocolMessageType('TrainParameterRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINPARAMETERREQUEST,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainParameterRequest)
  })
_sym_db.RegisterMessage(TrainParameterRequest)

TrainParameterResponse = _reflection.GeneratedProtocolMessageType('TrainParameterResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINPARAMETERRESPONSE,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainParameterResponse)
  })
_sym_db.RegisterMessage(TrainParameterResponse)

TrainDataRequest = _reflection.GeneratedProtocolMessageType('TrainDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINDATAREQUEST,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainDataRequest)
  })
_sym_db.RegisterMessage(TrainDataRequest)

TrainDataResponse = _reflection.GeneratedProtocolMessageType('TrainDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINDATARESPONSE,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainDataResponse)
  })
_sym_db.RegisterMessage(TrainDataResponse)

TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

TrainResultRequest = _reflection.GeneratedProtocolMessageType('TrainResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESULTREQUEST,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainResultRequest)
  })
_sym_db.RegisterMessage(TrainResultRequest)

TrainResultResponse = _reflection.GeneratedProtocolMessageType('TrainResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESULTRESPONSE,
  '__module__' : 'protocol.jyservice_pb2'
  # @@protoc_insertion_point(class_scope:JYService.TrainResultResponse)
  })
_sym_db.RegisterMessage(TrainResultResponse)



_JYSERVICE = _descriptor.ServiceDescriptor(
  name='JYService',
  full_name='JYService.JYService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=522,
  serialized_end=842,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrainParameter',
    full_name='JYService.JYService.TrainParameter',
    index=0,
    containing_service=None,
    input_type=_TRAINPARAMETERREQUEST,
    output_type=_TRAINPARAMETERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TrainData',
    full_name='JYService.JYService.TrainData',
    index=1,
    containing_service=None,
    input_type=_TRAINDATAREQUEST,
    output_type=_TRAINDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='JYService.JYService.Train',
    index=2,
    containing_service=None,
    input_type=_TRAINREQUEST,
    output_type=_TRAINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TrainResult',
    full_name='JYService.JYService.TrainResult',
    index=3,
    containing_service=None,
    input_type=_TRAINRESULTREQUEST,
    output_type=_TRAINRESULTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JYSERVICE)

DESCRIPTOR.services_by_name['JYService'] = _JYSERVICE

# @@protoc_insertion_point(module_scope)
